### ISSUE TITLE
Only Unlock Supply Drop Items 

### ISSUE THREAD

**Issue by 19Aidan** [XLabsProject/s1x-client#682] opened 2023-04-17 02:51 UTC
This has been a major issue for me. I don't want to unlock all and I want to grind but however, I also want everything in the supply drops. BOIII client has a thing like this, and executed perfectly. I would love a feature like this someday! :)

**Comment by diamante0018** [comment] 2023-05-09 09:37
Duplicate of #578

**Closed by diamante0018** 2023-05-09 09:37 UTC
Labels: duplicate, wontfix
