### ISSUE TITLE
Killcam Issue on Server Side 

### ISSUE THREAD

**Issue by DoktorSAS** [XLabsProject/s1x-client#56] opened 2021-04-02 09:30 UTC
### Killcam Issue
Right now it's not a huge bug, but it's annoying to the trickshotting community. Who are currently the ones paying the most interest to the project.
Clip #1: https://twitter.com/Dibs805/status/1377853809314033665
Clip #2: https://streamable.com/hta0ax
I tried rebuilding the exe but the problem persists only server side. If I load the same mod and create a private one no problem arises but if I load it server side something goes wrong in the killcam. Everything works correctly except the killcam. 
Not a priority as a bug but it's always best to report issues.

**Comment by sortileges** [comment] 2021-04-02 09:46
Duplicate of #53, and this should have been fixed with #54. Are you sure you rebuilt after [this commit](https://github.com/XLabsProject/s1x-client/commit/eab6d9efa5389426a962164445c6a8ba3dda095c) was made?

**Comment by DoktorSAS** [comment] 2021-04-02 13:07
I hadn't seen it, weird I recloned the project to make sure I had everything. Apparently that part is missing there. 
I will now try cloning the project with that additional piece. 
@sortileges

**Comment by momo5502** [comment] 2021-04-09 07:23
This issue has been resolved on the develop branch. It's not perfect, but fixing this completely is too much effort.

**Closed by momo5502** 2021-04-09 07:23 UTC
Labels: bug, wontfix
