### ISSUE TITLE
setteamscore not working as intended

### ISSUE THREAD

**Issue by bradstv** [XLabsProject/s1x-client#46] opened 2021-03-24 00:28 UTC
When utilizing ```game:setteamscore(player.team, value)```, the team score updates in the players HUD, however, the "actual" team score value doesn't update. 

For example, 
if ```game:setteamscore(player.team, 25)``` is called on a TDM game, the HUDs of all the players on the team updates to "25" for the score, however, if someone on the team gets a kill, the score reverts to its old value (actual value). 

Example script: 
```lua 
function player_spawned(player)
    game:setteamscore(player.team, 25)
end

function player_connected(player)
    player:onnotifyonce("spawned_player", function() player_spawned(player) end)
end

level:onnotify("connected", player_connected)
```

![example](https://user-images.githubusercontent.com/75509403/112235772-b394b000-8c15-11eb-872e-895df5112628.gif)

As you can see in the GIF above, both teams start with 25 kills and when a player gets a kill, instead of the value updating to 26, the value goes to 1.

**Comment by momo5502** [comment] 2021-03-24 06:58
It's hard to categorize this issue. This is not really a bug, even if it seems so

The game's logic has an internal kill counter. If you kill someone, it updates the internal counter and according to that, it updates the teamscore on the hud. 
Changing the teamscore yourself, obviously changes the hud, but not the kill counter of the game. Once you kill someone, the game will update its internal counter and thus the hud based on that counter, which will override your value. This function is only meaningful if you create your own gamemode.

**Comment by bradstv** [comment] 2021-03-24 07:10
> It's hard to categorize this issue. This is not really a bug, even if it seems so
> 
> The game's logic has an internal kill counter. If you kill someone, it updates the internal counter and according to that, it updates the teamscore on the hud.
> Changing the teamscore yourself, obviously changes the hud, but not the kill counter of the game. Once you kill someone, the game will update its internal counter and thus the hud based on that counter, which will override your value. This function is only meaningful if you create your own gamemode.

I see, so its an internal core game issue, so do I close the this thread?

**Comment by momo5502** [comment] 2021-03-24 07:12
Yeah, I will close it. setteamscore is definitely working as intended, it's just an interface for the hud, but you are using it, just like the game is using for its gamemode logic.

**Closed by momo5502** 2021-03-24 07:12 UTC
