### ISSUE TITLE
Game crashes when trying to load into online matches 

### ISSUE THREAD

**Issue by suprvillain** [XLabsProject/s1x-client#580] opened 2023-01-18 03:26 UTC
I have been trying to load into a multiplayer match and play.

Every time I try to load into a multiplayer match my game will load until half way and then crash to the menu giving me this error "error: fatal error (0xc0000005) at 0x00000001406876a" this is preventing me from playing online matches,

I'm on v2.1.0 of s1x

It ONLY crashes when I try to load into matches with other players
[s1x-crash-2-2023-01-17-22-08-57.zip](https://github.com/XLabsProject/s1x-client/files/10441814/s1x-crash-2-2023-01-17-22-08-57.zip)

**Comment by diamante0018** [comment] 2023-01-18 09:41
Hi, I will close this issue in a couple of days if you do not follow the correct template found here [get-help](https://github.com/XLabsProject/s1x-client/blob/develop/.github/ISSUE_TEMPLATE/get-help.md).

**Comment by suprvillain** [comment] 2023-01-18 11:23
> Hi, I will close this issue in a couple of days if you do not follow the correct template found here [get-help](https://github.com/XLabsProject/s1x-client/blob/develop/.github/ISSUE_TEMPLATE/get-help.md).

ok 1 sec sorry

**Comment by suprvillain** [comment] 2023-01-18 11:25
> Hi, I will close this issue in a couple of days if you do not follow the correct template found here [get-help](https://github.com/XLabsProject/s1x-client/blob/develop/.github/ISSUE_TEMPLATE/get-help.md).

is this ok what else do i need to change?

**Comment by suprvillain** [comment] 2023-01-18 13:40
> Fill out the template I linked to you and post it here. I mainly want to know about the version of S1x you are using.

v2.1.0 

btw im in the discord if it would be easier for you to talk there

**Comment by diamante0018** [comment] 2023-01-22 14:22
This is a duplicate of #165 
There is no know fix or workaround. Closing this so we only have one issue opened for tracking this.

**Closed by diamante0018** 2023-01-22 14:22 UTC
Labels: bug
